### PR TITLE
Update branch name from master to main in links

### PR DESCRIPTION
**Pull request by FantasqueX**

### CODE REVIEW

**Comment by banach-space** [comment]
Hi @FantasqueX , thank you for preparing this! Would you mind updating the branch name everywhere in `README.md`?

**Comment by FantasqueX** [comment]
I create another commit and I think all of the links in README.md have been updated.

**Comment by banach-space** [comment]
Great, thank you! Could you squash? I'll merge afterwards :)

**Comment by FantasqueX** [comment]
I rebased the commits. Could you check it again?

**Comment by banach-space** [comment]
This is much appreciated, thank you!

**Pull request merged**
