### PR TITLE
A way to invoke examples with modern LLVM and a legacy pass manager in README.md

### PR DESCRIPTION
**Pull request by myrrc**

### CODE REVIEW

**Comment by banach-space** [comment]
Hi @myrrc !

Many thanks for submitting this. I'm not sure whether you are aware, but [the legacy PM is being deprecated in LLVM 14](https://releases.llvm.org/14.0.0/docs/ReleaseNotes.html#changes-to-the-llvm-ir). And **llvm-tutor** is almost ready to [move to LLVM 14](https://github.com/banach-space/llvm-tutor/tree/release_14) too. So, I'm not sure whether it's worth adding more documentation that's specifically for the legacy PM. WDYT?

-Andrzej

**Comment by myrrc** [comment]
Yep, I'm aware. Unfortunately, for some use cases you can't switch to the new pass manager. For example, I have a pass that should be loaded as early as possible and process on module level.

If using old pass manager, it's as easy as `    "-O0 -flegacy-pass-manager
    -Xclang -load -Xclang pass.so
    -mllvm -pass-option")`.

However, there is no ability to do it with new pass manager yet (you can load a plugin with `fpass-plugin`, but the registration callbacks don't allow you to load it soon). You only can register the pass as an optimization pass which operates on O1 or higher.

However, it's totally up to you.

**Comment by banach-space** [comment]
Thanks for your quick reply!

> If using old pass manager, it's as easy as "-O0 -flegacy-pass-manager -Xclang -load -Xclang pass.so -mllvm -pass-option").
>
> However, there is no ability to do it with new pass manager yet (you can load a plugin with fpass-plugin, but the registration callbacks don't allow you to load it soon). You only can register the pass as an optimization pass which operates on O1 or higher.

I'm familiar with these limitations and this is unfortunate. I'm not sure how to best support users like you - the legacy pass manager is already deprecated in LLVM 14 and will be unavailable for optimisaiton pipelines in LLVM 15. As I would like **llvm-tutor** to be aligned with the latest release of LLVM, I intend to remove all references to the legacy PM once that's released.

Just based on your examples -  is it loading via `clang` that you are most concerned about? For the sake of simplicity, I don't really document any of that in **llvm-tutor** just yet. But once I can focus on just one pass manager, that should be easier :)

Please don't get me wrong, I really appreciate the contribution and you bringing this up! But I think that the more future-proof approach would be to:
* avoid adding new "legacy PM" references,
* start documenting the usage of pass plugins from Clang perspective.

-Andrzej

**Comment by myrrc** [comment]
Looks likes you solution is the most reasonable. 

>  is it loading via clang that you are most concerned about
Yeah, I'm trying to build a pass that would be easy to integrate into compiler pipelines as a shared library. Maybe the Universe tells me I should implement needed APIs myself in LLVM.

Taking into account that, I'm closing this PR.

**Pull request closed without merging**
