### PR TITLE
Run the FindFCmpEq pass with -S argument with new PM

### PR DESCRIPTION
**Pull request by xgupta**
Without -S argument we are getting bitcode to the terminal console.

### CODE REVIEW

**Comment by banach-space** [comment]
Hi @xgupta , thanks for preparing this! Would you be able to update the instructions for the legacy PM as well? I believe that it's a similar situation.

-Andrzej

**Comment by xgupta** [comment]
Hi @banach-space , IIRC legacy PM have -analyze option set which only emit .ll output to the standard output. I think that behavior is correct.

-Shivam

**Comment by banach-space** [comment]
Actually, I think that you might be after `-disable-output` here. Sorry for not realising earlier!

-Andrzej

**Comment by xgupta** [comment]
Oh, yes correct I was confused, I passed a little faster, but -disable-output is not printing any analysis output on the console? 

no

**Comment by xgupta** [comment]
> Hi @banach-space , IIRC legacy PM have -analyze option set which only emit .ll output to the standard output. I think that behavior is correct.
> 
> -Shivam

correction - it prints analysis output, not .ll file which is correct behaviour :)

rrrr

**Comment by banach-space** [comment]
Please squash, update the commit msg/description and then we can merge :)

**Comment by xgupta** [comment]
in favor of https://github.com/banach-space/llvm-tutor/pull/41

**Comment by c2hpxq** [comment]
> Oh, yes correct I was confused, I passed a little faster, but even after -disable-output, FindFCmpEq is not printing any analysis output on the console?
> 
> no

Hi,
I'm working on MacOS and I find that FindFCmpEq pass doesn't work under new pass manager mode.(i.e., no output after running `$LLVM_DIR/bin/opt --load-pass-plugin <build_dir>/lib/libFindFCmpEq.so --passes="print<find-fcmp-eq>" -disable-output input_for_fcmp_eq.ll`)

The legacy pass manager works just fine.

From the screen shot you take, it seems that you faced the same situation?
Is there a bug in implementation of FindFCmpEq's new pass manager mode?

This is my result:
WX20210811-004544@2x

**Pull request closed without merging**
