### PR TITLE
[NFC] Fix typo in `MergeBB` pass documentation

### PR DESCRIPTION
**Pull request by unterumarmung**

### CODE REVIEW

**Comment by banach-space** [comment]
Hi @unterumarmung , many thanks for this patch! "Iff" was intentional and means ["if and only if"](https://en.wikipedia.org/wiki/If_and_only_if) :) Happy to replace it with the expanded version!

-Andrzej

**Comment by unterumarmung** [comment]
Sorry for my bad English :(

**Comment by banach-space** [comment]
> Sorry for my bad English :)

Your English is perfectly fine, it's just a bit of a Maths jargon ;-) What shall we do here? Close this PR?

**Comment by unterumarmung** [comment]
Sure!

**Pull request closed without merging**
